name: moment_dart
description: moment.js port for dart
version: 0.1.3
homepage: https://github.com/theirontnt/moment_dart

environment:
  sdk: ">=2.15.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
