name: moment_dart
description: Immutable DateTime subclass for easier interaction with DateTime objects. Supports multiple localizations to convert DateTime into human-readable format
version: 0.10.5
homepage: https://github.com/theironbatka/moment_dart
issue_tracker: https://github.com/theironbatka/moment_dart/issues

environment:
  sdk: ">=2.17.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
