name: moment_dart
description: A package that turns DateTime into human-readable format. An attempt to port moment.js to dart. Supports multiple localizations (en_US, ko_KO, mn_MN, de_DE, more to be added..)
version: 0.6.0+1
homepage: https://github.com/theirontnt/moment_dart

environment:
  sdk: ">=2.15.0 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
